name: syhunt test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Check Syhunt Installation
        run: |
          if (!(Get-Command "Start-CodeScan" -ErrorAction SilentlyContinue)) {
            Write-Error "Syhunt is not installed or not properly configured on the runner"
            exit 1
          }
      - run: Start-CodeScan -output 'report.pdf'

      - name: 'Syhunt Report'
        uses: actions/upload-artifact@v2
        if: failure()
        with:
         name: syhunt-report
         path: report.pdf
         if-no-files-found: error